fix_msg_types_table = {
   '0' : 'Heartbeat',
   '1' : 'Test Request',
   '2' : 'Resend Request',
   '3' : 'Reject',
   '4' : 'Sequence Reset',
   '5' : 'Logout',
   '6' : 'Indication of Interest',
   '7' : 'Advertisement',
   '8' : 'Execution Report',
   '9' : 'Order Cancel Reject',
   'a' : 'Quote Status Request',
   'A' : 'Logon',
   'b' : 'Quote Acknowledgement',
   'B' : 'News',
   'c' : 'Security Definition Request',
   'C' : 'Email',
   'd' : 'Security Definition',
   'D' : 'Order - Single',
   'e' : 'Security Status Request',
   'E' : 'Order - List',
   'f' : 'Security Status',
   'F' : 'Order Cancel Request',
   'g' : 'Trading Session Status Request',
   'G' : 'Order Cancel/Replace Request',
   'h' : 'Trading Session Status',
   'H' : 'Order Status Request',
   'i' : 'Mass Quote',
   'j' : 'Business Message Reject',
   'J' : 'Allocation',
   'k' : 'Bid Request',
   'K' : 'List Cancel Request',
   'l' : 'Bid Response',
   'L' : 'List Execute',
   'm' : 'List Strike Price',
   'M' : 'List Status Request',
   'N' : 'List Status',
   'P' : 'Allocation ACK',
   'Q' : 'Don\'t Know Trade',
   'R' : 'Quote Request',
   'S' : 'Quote',
   'T' : 'Settlement Instructions',
   'V' : 'Market Data Request',
   'W' : 'Market Data - Snapshot/Full Refresh',
   'X' : 'Market Data - Incremental Refresh',
   'Y' : 'Market Data Request Reject',
   'Z' : 'Quote Cancel'
}